### ISSUE TITLE
Deploy your NextJs App tweaks 

### ISSUE THREAD

**Issue by technophile-04** [scaffold-eth/se2-docs#11]
![Screenshot 2023-08-06 at 4 33 10 PM](https://github.com/scaffold-eth/se2-docs/assets/80153681/2fbdb761-74d3-4ffb-915d-dba52fecdf39)

1 . Should we make `yarn vercel` and more prominent and easy copy-pastable ? 

Something like : 

If you want to deploy directly from the CLI, run : 
```
yarn vercel 
```
follow the steps to deploy to Vercel. Once you log in (email, github, etc), the default options should work. It'll give you a public URL.

If you want to redeploy to the same production URL you can run  : 
```
yarn vercel --prod. 
```
> HINT : If you omit the `--prod` flag it will deploy it to a preview/test URL.

---

2 . Kind of nitpick and can be ignored : 

In the right sidebar under `Scaffold Configuration` can we nest its configuration keys like `targetNetwork` etc ? 

![Screenshot 2023-08-06 at 5 23 11 PM](https://github.com/scaffold-eth/se2-docs/assets/80153681/276c2556-cbc8-4947-b0ac-8bbe06987de9)

But please free to close this issue if you think it might add a lot of sound to that section  🙌

**Comment by Pabl0cks** [comment]
I'm creating a PR with those changes, if you see that configuration attributes are too big now in the content, we can always roll back those changes.

![image](https://github.com/scaffold-eth/se2-docs/assets/55535804/8193a3b4-4a7c-4c3f-bb36-ef28e7769118)

**Comment by technophile-04** [comment]
Closed via #14
