### ISSUE TITLE
Add information about useScaffoldEventSubscriber listener

### ISSUE THREAD

**Issue by rin-st** [scaffold-eth/se2-docs#18]
listener is cached on the first render, so all the state changes depending on prev values inside it should be described as functions

when using `setState({...prevValue, a: 'b'})`, `prevValue` always be the same.

`setState(prevValue => ({...prevValue, a: 'b'})` works as expected.

It's difficult to debug, so I believe it should be in docs.

example: https://github.com/scaffold-eth/se-2-challenges/pull/76/commits/621be9503d98db236c63792670383014c938013d

**Comment by technophile-04** [comment]
Tysm @rin-st 🙌!! Just added a note about this in `useScaffoldEventSusbscriber`  hook in docs please feel free to re-open / make PR if I have mistaken something or something can be improved 🙌
