### ISSUE TITLE
Add options for different package managers in CLI

### ISSUE THREAD

**Issue by WiseMrMusa** [scaffold-eth/se2-docs#21]
The current default way of creating is using ```npx create-eth@latest``` but I created it using ```bunx create-eth@latest``` and it was very fast. However, there is only one package installer which is yarn. 

It will be better if developers can select which package to install with either 

- npm
- pnpm
- yarn or 
- bun (which I want to use)

Thanks.

**Comment by carletex** [comment]
We might support using any package manager when the CLI is merged: https://github.com/scaffold-eth/scaffold-eth-2/pull/413

Right now it's coupled with yarn.
