### ISSUE TITLE
Add Links to main Components in Intro

### ISSUE THREAD

**Issue by OwlWilderness** [scaffold-eth/se2-docs#27]
Hi - 
Can we add links for the main components in Intro?

The following commit in my repo adds links to to the docs page of the component and has a link to the components page for Daisy.

I originally thought to point to the main page but figured many devs might just go to the docs page anyway.

commit:
https://github.com/OwlWilderness/se2-docs/commit/6adf0aeec74e4508c55411e20b0cba96a3ab8544

example:
https://github.com/OwlWilderness/se2-docs/blob/intro-links/docs/intro.md

Thanks

**Comment by technophile-04** [comment]
completed in #28
