### ISSUE TITLE
Add details / section about adding externalContracts

### ISSUE THREAD

**Issue by technophile-04** [scaffold-eth/se2-docs#35]
Once we merge https://github.com/scaffold-eth/scaffold-eth-2/pull/592, it would be really helpful if we add section / page on how to add / interact with external contract  maybe we add it #25 section

**Comment by carletex** [comment]
Another option could be to add it inside the «🛠 Interacting with your Smart Contracts
». 

We already have:

> If you need to interact with external contracts, you can use wagmi directly, or add external contract data to your deployedContracts.ts file.

Maybe we can just tweak that.
