### ISSUE TITLE
support for avalanche

### ISSUE THREAD

**Issue by rgutierrezatx** [scaffold-eth/se2-docs#37]
add support for avalanche c-chain

**Comment by Pabl0cks** [comment]
Hi @rgutierrezatx! Thanks for the request, but the correct repo for ask for this feature would be [scaffold-eth-2 repo](https://github.com/scaffold-eth/scaffold-eth-2).

You can create a [Request Feature Issue](https://github.com/scaffold-eth/scaffold-eth-2/discussions/new?category=ideas) on there, and we'll discuss on the viability of it.

Closing this.
