### ISSUE TITLE
"yarn install" fails with 404

### ISSUE THREAD

**Issue by catssquared** [scaffold-eth/se2-docs#43]
Following the README instructions, I ran "yarn install" in the root directory of freshly cloned repo and the command terminated with:

"Error: https://codeload.github.com/hugomrdias/concat-stream/tar.gz/057bc7b5d6d8df26c8cf00a3f151b6721a0a8034: Request failed "404 Not Found""

**Comment by carletex** [comment]
@catssquared are you using the `git clone` method or the `npx create-eth@latest` method?

**Comment by catssquared** [comment]
@carletex the `git clone` method, sirrah.

i re-ran `yarn install` and it completed successfully. maybe my yarn was broken?

going to close this...

thank you for your help :)
